In [1]:
import pandas as pd

In [3]:
electors_df = pd.read_csv(r'C:\Users\Neil\Documents\Projects\Electoral-PH\Electoral-PH\image_creator\static\data\2010_Reps.csv', index_col=0)
electors_df.head()

   province_id  electors
0            1         1
1            2         2
2            3         2
3            4         1
4            5         3

In [5]:
provinces_df = pd.read_csv(r'C:\Users\Neil\Documents\Projects\Electoral-PH\Electoral-PH\image_creator\static\data\Provinces.csv', index_col=0)
provinces_df.head()

   province_id          Province
0            1              Abra
1            2  Agusan del Norte
2            3    Agusan del Sur
3            4             Aklan
4            5             Albay

In [7]:
df = pd.merge(electors_df, provinces_df, on='province_id')
df = df[['province_id', 'Province', 'electors']]
df.head()

   province_id          Province  electors
0            1              Abra         1
1            2  Agusan del Norte         2
2            3    Agusan del Sur         2
3            4             Aklan         1
4            5             Albay         3

In [10]:
df = df.rename({'Province':'province'})

In [11]:
df.to_csv(r'C:\Users\Neil\Documents\Projects\Electoral-PH\Electoral-PH\image_creator\static\data\2010_Reps.csv')

In [9]:
provinces_df.to_csv(r'C:\Users\Neil\Documents\Projects\Electoral-PH\Electoral-PH\image_creator\static\data\Provinces.csv')